# Header
menu:
  Home: /
  Archives: /archives
  Book: /booklist
  About: /about
rss: /atom.xml

# Content
excerpt_link: Read More
fancybox: false
mathjax: false

# Sidebar
sidebar: right
widgets:
- recent_posts
- category
#- tag
- archive
- tagcloud
- links
- archive



# Links
links:
  MacTalk: http://macshuo.com/
  Android官网: http://developer.android.com/index.html
  稀土掘金: http://gold.xitu.io/#/
  开发技术最前线: http://www.devtf.cn/
  App开发日报: http://app.memect.com/
  Android开发周报: http://androidweekly.cn/
  GankIO: http://gank.io
  泡在网上的日子: http://www.jcodecraeer.com/
  伯乐在线: http://android.jobbole.com/
  StormZhang: http://stormzhang.github.io
  张兴业: http://my.csdn.net/xyz_lmn
  AndroidStyle: https://blog.stylingandroid.com

# Miscellaneous
google_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins: 
fb_app_id:
# Baidu Analytics ID
baidu_analytics: c01cc8a847f9091e2448fb88ca55ceae

wechat_subscriber:
  enabled: true
  qcode: http://7xj9f0.com1.z0.glb.clouddn.com/md/1469632917108.png
  description: 关注TechForAndroid的公众号

since: 2014
# Duoshuo
duoshuo_shortname:  ownwell

# Baidu share
baidushare: true