## Services
google_analytics:
duoshuo: 'jingege'

## Meta
rss: /atom.xml
favicon: /favicon.ico
icon: /favicon.ico
source_url: https://github.com/jingege/jingege.github.com/tree/source/source/
license:
  name: 'CC BY-NC-SA 3.0'
  url: 'http://creativecommons.org/licenses/by-nc-sa/3.0/cn'

## Menus
menus:
  '首页': /
  '关于我': /about
  '书单': /booklist
  '小抄': /cheatsheet

right_menus:
  'RSS': /atom.xml
  'fork on Github':
    target: '_blank'
    href: 'http://github.com/jingege'

## Banners && Widgets
banners:
  jade: |

    | 小站重新装修，欢迎到访。

widgets:
  -
    markdown: |
      博主是一个不是很聪明的码农。完美主义者，强迫症中期。这里会记录一些回忆和点滴，以博为镜。

      武器库：

      * [MacBook Pro](http://www.apple.com/cn/macbook-pro/)
      * [Intellij IDEA](https://www.jetbrains.com/idea/)
      * [iTerm2](https://www.iterm2.com/)
      * [Shtion](http://shtion.info)
      * [Java](https://www.oracle.com/java/)
      * [Scala](http://scala-lang.org/)

  -
    tags: true

  -
    archives: true

  -
    copyright: true

## SNS (Work in progress)
sns:
  qq: '232772720'
  qun: ''
  v2ex: ''
  mobile: ''
  github: 'jingege'
  keybase: ''
  zhihu: ''
  google_plus: ''
  segmentfault: 'jysperm'
  twitter: 'jysperm'
  bitcoin: '13v2BTCMZMHg5v87susgg86HFZqXERuwUd'


 # Theme version
version: 0.4.5

# Highlight theme
highlight_theme: jgg
